apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: rapharch
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "9999"
  GRPC_PORT: "50051"
  USE_REDIS: "true"
  FRONTEND_URL: "https://rapharch.com"
