-- CreateTable
CREATE TABLE "products" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "productCode" TEXT,
    "description" TEXT,
    "shortDescription" TEXT,
    "disclaimer" TEXT,
    "ingredients" TEXT,
    "additionalDetails" TEXT,
    "materialCare" TEXT,
    "showIngredients" BOOLEAN NOT NULL DEFAULT false,
    "showDisclaimer" BOOLEAN NOT NULL DEFAULT false,
    "showAdditionalDetails" BOOLEAN NOT NULL DEFAULT false,
    "showMaterialCare" BOOLEAN NOT NULL DEFAULT false,
    "sku" TEXT,
    "barcode" TEXT,
    "upc" TEXT,
    "ean" TEXT,
    "isbn" TEXT,
    "trackQuantity" BOOLEAN NOT NULL DEFAULT true,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
    "allowBackorder" BOOLEAN NOT NULL DEFAULT false,
    "manageStock" BOOLEAN NOT NULL DEFAULT true,
    "weight" DOUBLE PRECISION,
    "weightUnit" TEXT NOT NULL DEFAULT 'kg',
    "images" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "videos" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "thumbnail" TEXT,
    "seoTitle" TEXT,
    "seoDescription" TEXT,
    "seoKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "canonicalUrl" TEXT,
    "robotsMeta" TEXT DEFAULT 'index,follow',
    "seoFriendlyImageFilename" TEXT,
    "imageAltText" TEXT,
    "productSchema" TEXT,
    "brandSchema" TEXT,
    "breadcrumbSchema" TEXT,
    "itemListSchema" TEXT,
    "faqSchema" TEXT,
    "ogTitle" TEXT,
    "ogDescription" TEXT,
    "ogImage" TEXT,
    "twitterCardMeta" TEXT,
    "productDescription" TEXT,
    "faqs" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDigital" BOOLEAN NOT NULL DEFAULT false,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "isNew" BOOLEAN NOT NULL DEFAULT false,
    "isOnSale" BOOLEAN NOT NULL DEFAULT false,
    "isBestSeller" BOOLEAN NOT NULL DEFAULT false,
    "isSales" BOOLEAN NOT NULL DEFAULT false,
    "isNewSeller" BOOLEAN NOT NULL DEFAULT false,
    "isFestivalOffer" BOOLEAN NOT NULL DEFAULT false,
    "visibility" TEXT NOT NULL DEFAULT 'VISIBLE',
    "publishedAt" TIMESTAMP(3),
    "requiresShipping" BOOLEAN NOT NULL DEFAULT true,
    "shippingClass" TEXT,
    "freeShipping" BOOLEAN NOT NULL DEFAULT false,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "taxClass" TEXT,
    "categoryId" TEXT NOT NULL,
    "brandId" TEXT,
    "customFields" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "products_slug_key" ON "products"("slug");

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
