import { Router } from 'express';
import { authenticateToken, requireAdmin } from '../middlewares/auth';
import { healthCheck } from '../controllers/health.controller';
import aboutRoutes from './about.routes';
import analyticsRoutes from './analytics.routes';
import authRoutes from './auth.routes';
import bannerRoutes from './banner.routes';
import cartRoutes from './cart.routes';
import categoryRoutes from './category.routes';
import categoryGridRoutes from './category-grid.routes';
import contentRoutes from './content.routes';
import dualCardSectionRoutes from './dual-card-section.routes';
import editorialSectionRoutes from './editorial-section.routes';
import featuredSectionRoutes from './featured-section.routes';
import salesBannerRoutes from './sales-banner.routes';
import followSectionRoutes from './follow-section.routes';
import footerCatalogRoutes from './footer-catalog.routes';
import footerSectionRoutes from './footer-section.routes';
import heroBannerRoutes from './hero-banner.routes';
import heroSlideRoutes from './hero-slide.routes';
import imageGridRoutes from './image-grid.routes';
import inventoryRoutes from './inventory.routes';
import jsonLdRoutes from './json-ld.routes';
import navigationRoutes from './navigation.routes';
import orderRoutes from './order.routes';
import paymentRoutes from './payment.routes';
import productRoutes from './product.routes';
import rewardRoutes from './reward.routes';
import seoRoutes from './seo.routes';
import settingsRoutes from './settings.routes';
import staffRoutes from './staff.routes';
import uploadRoutes from './upload.routes';
import userRoutes from './user.routes';
import userRewardRoutes from './userReward.routes';
import colorThemeRoutes from './color-theme.routes';
import deliveryRoutes from './delivery.routes';
import notificationRoutes from './notification.routes';
import posRoutes from './pos.routes';
import addressRoutes from './address.routes';
import publicUserRoutes from './public-user.routes';
import couponRoutes from './coupon.routes';
import faqRoutes from './faq.routes';
import shippingRoutes from './shipping.routes';
import storeRoutes from './store.routes';
import storeLocationRoutes from './store-location.routes';
import contactRoutes from './contact.routes';
import contactPageRoutes from './contact-page.routes';
import attributeOptionRoutes from './attribute-option.routes';
import promotionalBannerRoutes from './promotional-banner.routes';
import featureConfigRoutes from './feature-config.routes';
import threeImageGridRoutes from './three-image-grid.routes';
import categoryTileGridRoutes from './category-tile-grid.routes';
import shortDescriptionRoutes from './short-description.routes';
import womenItemsRoutes from './women-items.routes';

const router: Router = Router();

router.get('/health', healthCheck);

// Public routes (no auth required)
router.use('/auth', authRoutes);
router.use('/users', publicUserRoutes);
router.use('/content', contentRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/user-rewards', userRewardRoutes);
router.use('/orders', orderRoutes);
router.use('/cart', cartRoutes);
router.use('/faqs', faqRoutes);
router.use('/contact', contactRoutes);
router.use('/attribute-options', attributeOptionRoutes);

// Public read-only routes for storefront
router.use('/public/about', aboutRoutes);
router.use('/public/banners', bannerRoutes);
router.use('/public/hero-slides', heroSlideRoutes);
router.use('/public/hero-banners', heroBannerRoutes);
router.use('/public/image-grid', imageGridRoutes);
router.use('/shipping', shippingRoutes);
router.use('/store-section', storeRoutes);
router.use('/public/contact-page', contactPageRoutes);
router.use('/public/store-locations', storeLocationRoutes);
router.use('/public/featured-sections', featuredSectionRoutes);
router.use('/public/category-grid', categoryGridRoutes);
router.use('/public/navigation', navigationRoutes);
router.use('/public/footer-catalog', footerCatalogRoutes);
router.use('/public/footer-section', footerSectionRoutes);
router.use('/public/follow-section', followSectionRoutes);
router.use('/public/editorial-sections', editorialSectionRoutes);
router.use('/public/sales-banners', salesBannerRoutes);
router.use('/public/dual-card-sections', dualCardSectionRoutes);
router.use('/public/coupons', couponRoutes);
router.use('/public/promotional-banners', promotionalBannerRoutes);
router.use('/public/feature-configs', featureConfigRoutes);
router.use('/public/three-image-grid', threeImageGridRoutes);
router.use('/public/category-tile-grid', categoryTileGridRoutes);

// Protected routes (require authentication)
const authMiddleware = [authenticateToken];
const adminMiddleware = [authenticateToken, requireAdmin];

router.use('/staff', ...adminMiddleware, staffRoutes);
router.use('/upload', ...adminMiddleware, uploadRoutes);
router.use('/analytics', ...authMiddleware, analyticsRoutes);
router.use('/rewards', ...adminMiddleware, rewardRoutes);
router.use('/payments', paymentRoutes);
router.use('/json-ld', jsonLdRoutes);
router.use('/notifications', ...authMiddleware, notificationRoutes);
router.use('/deliveries', ...authMiddleware, deliveryRoutes);
router.use('/user/addresses', addressRoutes);

// Admin-managed routes (require admin auth)
router.use('/about', ...adminMiddleware, aboutRoutes);
router.use('/inventory', ...adminMiddleware, inventoryRoutes);
router.use('/banners', ...adminMiddleware, bannerRoutes);
router.use('/hero-slides', ...adminMiddleware, heroSlideRoutes);
router.use('/hero-banners', ...adminMiddleware, heroBannerRoutes);
router.use('/image-grid', ...adminMiddleware, imageGridRoutes);
router.use('/category-grid', ...adminMiddleware, categoryGridRoutes);
router.use('/navigation', ...adminMiddleware, navigationRoutes);
router.use('/footer-catalog', ...adminMiddleware, footerCatalogRoutes);
router.use('/footer-section', ...adminMiddleware, footerSectionRoutes);
router.use('/follow-section', ...adminMiddleware, followSectionRoutes);
router.use('/featured-sections', ...adminMiddleware, featuredSectionRoutes);
router.use('/sales-banners', ...adminMiddleware, salesBannerRoutes);
router.use('/editorial-sections', ...adminMiddleware, editorialSectionRoutes);
router.use('/dual-card-sections', ...adminMiddleware, dualCardSectionRoutes);
router.use('/users', ...authMiddleware, userRoutes);
router.use('/color-theme', ...adminMiddleware, colorThemeRoutes);
router.use('/settings', ...authMiddleware, settingsRoutes);
router.use('/contact-page', ...adminMiddleware, contactPageRoutes);
router.use('/store-locations', ...adminMiddleware, storeLocationRoutes);
router.use('/seo', ...authMiddleware, seoRoutes);
router.use('/pos', ...adminMiddleware, posRoutes);
router.use('/coupons', ...adminMiddleware, couponRoutes);
router.use('/promotional-banners', ...adminMiddleware, promotionalBannerRoutes);
router.use('/feature-configs', ...adminMiddleware, featureConfigRoutes);
router.use('/three-image-grid', ...adminMiddleware, threeImageGridRoutes);
router.use('/category-tile-grid', ...adminMiddleware, categoryTileGridRoutes);
router.use('/short-description', shortDescriptionRoutes);
router.use('/women-items', womenItemsRoutes);

export default router;
