'use client';

import React from 'react';
import VariantMatrix from '../product/VariantMatrix';

interface VariantAttribute {
  id: string;
  name: string;
  type: 'color' | 'pattern' | 'size';
  options: Array<{
    id: string;
    name: string;
    value: string;
    image?: string;
  }>;
}

interface GeneratedVariant {
  id: string;
  name: string;
  sku: string;
  size: string;
  color: string;
  pattern: string;
  quantity: number;
  price?: number;
  comparePrice?: number;
  barcode?: string;
  images?: string[];
  isActive?: boolean;
  isDefault?: boolean;
}

interface MatrixVariant {
  id: string;
  combination: Record<string, string>;
  price: number;
  comparePrice?: number;
  stock: number;
  sku: string;
  barcode?: string;
  images: string[];
  isActive: boolean;
  isDefault: boolean;
}

interface CurrencyPrice {
  price: number;
  comparePrice?: number;
}

export interface VariantsTabProps {
  variantAttributes: VariantAttribute[];
  autoGeneratedVariants: GeneratedVariant[];
  currencyPrices: CurrencyPrice[];
  baseSku: string;
  onAttributesChange: (attributes: VariantAttribute[]) => void;
  onVariantsChange: (variants: GeneratedVariant[]) => void;
  errors: Record<string, string>;
  basePrice?: number;
  onBasePriceChange?: (price: number) => void;
}

const validateVariants = (
  autoGeneratedVariants: GeneratedVariant[]
): Record<string, string> => {
  const errors: Record<string, string> = {};
  if (autoGeneratedVariants.length > 0) {
    const invalidVariants = autoGeneratedVariants.filter(
      (v) => (v.quantity as number) < 1 || (v.price ?? 0) < 0
    );
    if (invalidVariants.length > 0) {
      errors.variants = `${invalidVariants.length} variant(s) have invalid stock (must be ≥1) or price (must be ≥0)`;
    }
  }
  return errors;
};

const VariantsTab: React.FC<VariantsTabProps> = React.memo(({
  variantAttributes,
  autoGeneratedVariants,
  currencyPrices,
  baseSku,
  onAttributesChange,
  onVariantsChange,
  errors,
  basePrice = 0,
  onBasePriceChange,
}) => {
  const effectiveBasePrice = currencyPrices?.[0]?.price ?? basePrice;

  const matrixVariants: MatrixVariant[] = autoGeneratedVariants.map((v) => {
    const combination: Record<string, string> = {};
    variantAttributes.forEach((attr) => {
      if (attr.type === 'color' && v.color) combination[attr.id] = v.color;
      if (attr.type === 'size' && v.size) combination[attr.id] = v.size;
      if (attr.type === 'pattern' && v.pattern) combination[attr.id] = v.pattern;
    });
    return {
      id: v.id,
      combination,
      price: v.price ?? effectiveBasePrice,
      comparePrice: v.comparePrice ?? currencyPrices?.[0]?.comparePrice,
      stock: v.quantity ?? 0,
      sku: v.sku || '',
      barcode: v.barcode || '',
      images: v.images || [],
      isActive: v.isActive ?? true,
      isDefault: v.isDefault ?? false,
    };
  });

  const handleMatrixVariantsChange = (variants: MatrixVariant[]) => {
    const colorAttrId = variantAttributes.find((a) => a.type === 'color')?.id;
    const sizeAttrId = variantAttributes.find((a) => a.type === 'size')?.id;
    const patternAttrId = variantAttributes.find((a) => a.type === 'pattern')?.id;
    const updatedVariants: GeneratedVariant[] = variants.map((v) => ({
      id: v.id,
      name: Object.values(v.combination).join(' - '),
      sku: v.sku,
      size: (sizeAttrId && v.combination[sizeAttrId]) || '',
      color: (colorAttrId && v.combination[colorAttrId]) || '',
      pattern: (patternAttrId && v.combination[patternAttrId]) || '',
      quantity: v.stock,
      price: v.price,
      comparePrice: v.comparePrice,
      barcode: v.barcode,
      images: v.images || [],
      isActive: v.isActive,
      isDefault: v.isDefault,
    }));
    onVariantsChange(updatedVariants);
  };

  return (
    <div className="space-y-6">
      {errors.variants && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-sm text-red-600">{errors.variants}</p>
        </div>
      )}
      {(currencyPrices.length === 0 || !onBasePriceChange) && (
        <div className="bg-gray-50 rounded-lg p-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Base Price (applies to all variants without individual price)
          </label>
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-900 text-sm">$</span>
            <input
              type="text"
              inputMode="decimal"
              value={basePrice}
              onChange={(e) => {
                const raw = e.target.value;
                if (!/^[0-9]*\.?[0-9]*$/.test(raw)) return;
                onBasePriceChange?.(raw === '' ? 0 : parseFloat(raw));
              }}
              onBlur={(e) => {
                const val = parseFloat(e.target.value) || 0;
                onBasePriceChange?.(val);
              }}
              className="w-full max-w-xs pl-7 pr-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-black"
              placeholder="0.00"
            />
          </div>
        </div>
      )}
      <VariantMatrix
        attributes={variantAttributes}
        onAttributesChange={onAttributesChange}
        variants={matrixVariants}
        onVariantsChange={handleMatrixVariantsChange}
        basePrice={effectiveBasePrice}
        baseSku={baseSku}
      />
    </div>
  );
});

VariantsTab.displayName = 'VariantsTab';

export { validateVariants };
export default VariantsTab;
