interface Product {
  id: string;
  name: string;
  slug: string;
  categoryId: string;
  price: number;
  originalPrice: number | null;
  discountPercent: number | null;
  images: string[];
  thumbnail: string | null;
  isNew: boolean;
  isActive: boolean;
  isFeatured: boolean;
  isOnSale: boolean;
  isBestSeller: boolean;
  gender: string | null;
  selectedSizes: string[] | null;
  selectedColors: string[] | null;
  category?: { id: string; name: string; slug: string };
}

export const hardcodedProducts: Product[] = [
  {
    id: '1',
    name: 'Oversized Cotton Shirt',
    slug: 'oversized-cotton-shirt',
    categoryId: '1',
    price: 89.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['XS', 'S', 'M', 'L'],
    selectedColors: ['#F5F5F0', '#1A1A1A', '#C4A882'],
    category: { id: '1', name: 'Tops', slug: 'tops' },
  },
  {
    id: '2',
    name: 'Tailored Wool Blazer',
    slug: 'tailored-wool-blazer',
    categoryId: '1',
    price: 245.00,
    originalPrice: 295.00,
    discountPercent: 17,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: true,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['S', 'M', 'L', 'XL'],
    selectedColors: ['#1B2A4A', '#3D3D3D'],
    category: { id: '1', name: 'Outerwear', slug: 'outerwear' },
  },
  {
    id: '3',
    name: 'Linen Wide-Leg Trousers',
    slug: 'linen-wide-leg-trousers',
    categoryId: '2',
    price: 135.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['XS', 'S', 'M', 'L'],
    selectedColors: ['#F5E6D3', '#6B7B5A'],
    category: { id: '2', name: 'Bottoms', slug: 'bottoms' },
  },
  {
    id: '4',
    name: 'Suede Chelsea Boots',
    slug: 'suede-chelsea-boots',
    categoryId: '3',
    price: 198.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['6', '7', '8', '9'],
    selectedColors: ['#C4956A', '#1A1A1A', '#6B2233'],
    category: { id: '3', name: 'Shoes', slug: 'shoes' },
  },
  {
    id: '5',
    name: 'Cropped Denim Jacket',
    slug: 'cropped-denim-jacket',
    categoryId: '1',
    price: 165.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: true,
    gender: 'Women',
    selectedSizes: ['XS', 'S', 'M', 'L'],
    selectedColors: ['#7BA3C4', '#1A1A1A'],
    category: { id: '1', name: 'Outerwear', slug: 'outerwear' },
  },
  {
    id: '6',
    name: 'Ribbed Knit Dress',
    slug: 'ribbed-knit-dress',
    categoryId: '4',
    price: 120.00,
    originalPrice: 150.00,
    discountPercent: 20,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: true,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['S', 'M', 'L'],
    selectedColors: ['#5A6B4A', '#C49A6C', '#1A1A1A'],
    category: { id: '4', name: 'Dresses', slug: 'dresses' },
  },
  {
    id: '7',
    name: 'Classic White Sneakers',
    slug: 'classic-white-sneakers',
    categoryId: '3',
    price: 145.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: true,
    gender: 'Unisex',
    selectedSizes: ['6', '7', '8', '9', '10', '11'],
    selectedColors: ['#FFFFFF', '#F5F5F0', '#1A1A1A'],
    category: { id: '3', name: 'Shoes', slug: 'shoes' },
  },
  {
    id: '8',
    name: 'Leather Crossbody Bag',
    slug: 'leather-crossbody-bag',
    categoryId: '5',
    price: 210.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['One Size'],
    selectedColors: ['#1A1A1A', '#8B4513', '#2F4F4F'],
    category: { id: '5', name: 'Accessories', slug: 'accessories' },
  },
  {
    id: '9',
    name: 'Merino Wool Sweater',
    slug: 'merino-wool-sweater',
    categoryId: '1',
    price: 175.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Men',
    selectedSizes: ['S', 'M', 'L', 'XL'],
    selectedColors: ['#696969', '#2F4F4F', '#8B4513'],
    category: { id: '1', name: 'Tops', slug: 'tops' },
  },
  {
    id: '10',
    name: 'Slim Fit Chinos',
    slug: 'slim-fit-chinos',
    categoryId: '2',
    price: 98.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Men',
    selectedSizes: ['30', '32', '34', '36'],
    selectedColors: ['#D2B48C', '#696969', '#2F4F4F'],
    category: { id: '2', name: 'Bottoms', slug: 'bottoms' },
  },
  {
    id: '11',
    name: 'Denim Jacket',
    slug: 'denim-jacket',
    categoryId: '1',
    price: 185.00,
    originalPrice: 220.00,
    discountPercent: 16,
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: true,
    isBestSeller: false,
    gender: 'Men',
    selectedSizes: ['S', 'M', 'L', 'XL'],
    selectedColors: ['#4169E1', '#1A1A1A'],
    category: { id: '1', name: 'Outerwear', slug: 'outerwear' },
  },
  {
    id: '12',
    name: 'Silk Blouse',
    slug: 'silk-blouse',
    categoryId: '1',
    price: 155.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1608236415057-fc4f2a4b4e4f?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['XS', 'S', 'M', 'L'],
    selectedColors: ['#FFE4E1', '#FFFFFF', '#1A1A1A'],
    category: { id: '1', name: 'Tops', slug: 'tops' },
  },
  {
    id: '13',
    name: 'Wool Scarf',
    slug: 'wool-scarf',
    categoryId: '5',
    price: 65.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Unisex',
    selectedSizes: ['One Size'],
    selectedColors: ['#8B0000', '#2F4F4F', '#696969', '#D2B48C'],
    category: { id: '5', name: 'Accessories', slug: 'accessories' },
  },
  {
    id: '14',
    name: 'Cargo Pants',
    slug: 'cargo-pants',
    categoryId: '2',
    price: 110.00,
    originalPrice: null,
    discountPercent: null,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80'],
    thumbnail: null,
    isNew: true,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    gender: 'Men',
    selectedSizes: ['30', '32', '34', '36'],
    selectedColors: ['#556B2F', '#696969', '#1A1A1A'],
    category: { id: '2', name: 'Bottoms', slug: 'bottoms' },
  },
  {
    id: '15',
    name: 'Leather Ankle Boots',
    slug: 'leather-ankle-boots',
    categoryId: '3',
    price: 230.00,
    originalPrice: 280.00,
    discountPercent: 18,
    images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80'],
    thumbnail: null,
    isNew: false,
    isActive: true,
    isFeatured: false,
    isOnSale: true,
    isBestSeller: false,
    gender: 'Women',
    selectedSizes: ['6', '7', '8', '9'],
    selectedColors: ['#1A1A1A', '#8B4513'],
    category: { id: '3', name: 'Shoes', slug: 'shoes' },
  },
];
