import { z } from 'zod';

export const createProductSchema = z.object({
  name: z.string().min(1).max(255),
  slug: z.string().min(1).max(255).regex(/^[a-z0-9-]+$/),
  productCode: z.string().optional(),
  categoryId: z.string().uuid(),
  subCategoryId: z.string().uuid().optional(),
  description: z.string().optional(),
  shortDescription: z.string().optional(),
  disclaimer: z.string().optional(),
  materialCare: z.string().optional(),
  gender: z.string().optional(),
  season: z.string().optional(),
  material: z.string().optional(),
  occasion: z.string().optional(),
  fitType: z.string().optional(),
  pattern: z.string().optional(),
  sleeveStyle: z.string().optional(),
  neckStyle: z.string().optional(),
  washCare: z.string().optional(),
  sku: z.string().optional(),
  barcode: z.string().optional(),
  upc: z.string().optional(),
  ean: z.string().optional(),
  isbn: z.string().optional(),
  trackQuantity: z.boolean().optional(),
  quantity: z.number().int().min(0).optional(),
  lowStockThreshold: z.number().int().min(0).optional(),
  allowBackorder: z.boolean().optional(),
  manageStock: z.boolean().optional(),
  price: z.number().optional(),
  originalPrice: z.number().optional(),
  costPrice: z.number().optional(),
  discountPercent: z.number().optional(),
  weight: z.number().optional(),
  weightUnit: z.string().optional(),
  dimensions: z.any().optional(),
  images: z.array(z.string()).optional(),
  videos: z.array(z.string()).optional(),
  thumbnail: z.string().optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  seoKeywords: z.array(z.string()).optional(),
  canonicalUrl: z.string().optional(),
  robotsMeta: z.string().optional(),
  seoFriendlyImageFilename: z.string().optional(),
  imageAltText: z.string().optional(),
  productSchema: z.any().optional(),
  brandSchema: z.any().optional(),
  breadcrumbSchema: z.any().optional(),
  itemListSchema: z.any().optional(),
  faqSchema: z.any().optional(),
  ogTitle: z.string().optional(),
  ogDescription: z.string().optional(),
  ogImage: z.string().optional(),
  twitterCardMeta: z.any().optional(),
  productDescription: z.string().optional(),
  faqs: z.any().optional(),
  isActive: z.boolean().optional(),
  isDigital: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
  isNew: z.boolean().optional(),
  isOnSale: z.boolean().optional(),
  isBestSeller: z.boolean().optional(),
  isSales: z.boolean().optional(),
  isNewSeller: z.boolean().optional(),
  isFestivalOffer: z.boolean().optional(),
  visibility: z.string().optional(),
  publishedAt: z.string().datetime().optional().or(z.string().max(0)),
  requiresShipping: z.boolean().optional(),
  shippingClass: z.string().optional(),
  freeShipping: z.boolean().optional(),
  taxable: z.boolean().optional(),
  taxClass: z.string().optional(),
  customFields: z.any().optional(),
  notes: z.string().optional(),
  isVariant: z.boolean().optional(),
  variantAttributes: z.any().optional(),
  selectedSizes: z.any().optional(),
  selectedColors: z.any().optional(),
  variants: z.any().optional(),
  tags: z.array(z.string()).optional(),
  currencyPrices: z.array(z.any()).optional(),
  pricingTiers: z.array(z.any()).optional(),
  attributes: z.array(z.any()).optional(),
});

export const updateProductSchema = createProductSchema.partial();

export const productQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().min(1).max(100).default(10),
  search: z.string().optional(),
  categoryId: z.string().uuid().optional(),
  isActive: z.enum(['true', 'false']).optional(),
  isFeatured: z.enum(['true', 'false']).optional(),
  isNew: z.enum(['true', 'false']).optional(),
  isOnSale: z.enum(['true', 'false']).optional(),
  isBestSeller: z.enum(['true', 'false']).optional(),
  isNewSeller: z.enum(['true', 'false']).optional(),
  isFestivalOffer: z.enum(['true', 'false']).optional(),
  isDigital: z.enum(['true', 'false']).optional(),
  sortBy: z.enum(['createdAt', 'updatedAt', 'name']).optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
});

export const bulkDeleteSchema = z.object({
  ids: z.array(z.string().uuid()).min(1),
});

export type CreateProductDTO = z.infer<typeof createProductSchema>;
export type UpdateProductDTO = z.infer<typeof updateProductSchema>;
export type ProductQueryDTO = z.infer<typeof productQuerySchema>;
export type BulkDeleteDTO = z.infer<typeof bulkDeleteSchema>;
